network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: yes
    enp2s0: {}
    enp3s0: {}
    enp4s0: {}
  bridges:
    br0:
      interfaces: [enp2s0, enp3s0, enp4s0]
      dhcp4: true
      parameters:
        stp: false
        forward-delay: 0
